apiVersion: v1
kind: Service
metadata:
  name: pihole-web
spec:
  selector:
    app: pihole
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
spec:
  selector:
    app: pihole
  ports:
    - port: 53
      targetPort: 53
      nodePort: 30053
      protocol: TCP
      name: dns-tcp
    - port: 53
      targetPort: 53
      nodePort: 30053
      protocol: UDP
      name: dns-udp
  type: NodePort
